spring:
  datasource:
    url: ${Url-Database}:3306/${DB-Name}?useSSL=true
    username: ${DB-username}
    password: ${DB-password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false

server:
  port: 8080

azure:
  keyvault:
    enabled: true
    uri: https://zeusfitkeyvault.vault.azure.net/auth
    client-id: 61c44725-383c-43a3-93c9-30e94374ec15
    client-key: V.q~NOT7o.KH5A4n2G9fbO3Rl4K~yYvx-z
    tenant-id: 2fcfe26a-bb62-46b0-b1e3-28f9da0c45fd

keycloak:
  realm: ZeusFit
  resource: spring-boot-zeusfit
  auth-server-url: https://keycloakzeusfit.azurewebsites.net
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username

